# Generated by Django 3.1.6 on 2021-02-05 17:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id_paciente', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, null=True)),
                ('nasc', models.DateField(null=True)),
                ('cpf', models.CharField(max_length=20, null=True)),
                ('end', models.CharField(max_length=255, null=True)),
                ('cep', models.CharField(max_length=20, null=True)),
                ('bairro', models.CharField(max_length=255, null=True)),
                ('cidade', models.CharField(max_length=50, null=True)),
                ('uf', models.CharField(max_length=50, null=True)),
                ('tel', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
